name: CI & Deploy

on:
  push:
    branches:
      - feat/*
      - fix/*
      - hotfix/*
      - develop
      - main

    paths:
      - ".github/workflows/*"
      - "back/**"

jobs:
  tests:
    name: Test back
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: back/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
